#!/bin/bash

./show_environment_info
echo

# Common adapted tests
./HelloWorld.sh -n 10
./QuickSort.sh -n 25 -a 10000
./QuickSort.sh -n 25 -a 25000
./QuickSort.sh -n 25 -a 50000
./ContactsBook.sh -n 10 --jvm-args -Xmx2048m --jvm-args -Xint -a 50 -a 100
./ContactsBook.sh -n 10 --jvm-args -Xmx2048m --jvm-args -Xint -a 50 -a 600
./ContactsBook.sh -n 10 --jvm-args -Xmx2048m --jvm-args -Xint -a 50 -a 1100

# Tests which will be better to run on some server
#./ImageHandling.sh -n 3 -a "`pwd`/test_sprite_images/"
#./NetworkEmulation.sh -n 2 -a 10000

